version: '3'
services:
  lambci:
    image: "lambci/lambda:provided"
    volumes:
        - ../../.build/local:/var/task:ro,delegated
        - ../../bootstrap:/opt/bootstrap:ro,delegated
        - ../../swift-shared-libs:/opt/swift-shared-libs:ro,delegated
    environment:
      - DOCKER_LAMBDA_STAY_OPEN=1
      - AWS_LAMBDA_FUNCTION_TIMEOUT=10
      - LAMB_CI_EXEC=1
    command:
      - PostgreSQLDemo.query
    ports:
     - "9001:9001"
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=username1
      - POSTGRES_PASSWORD=password1
      - POSTGRES_DB=demoDB